### ISSUE TITLE
Kotlin's ScriptEngine isn't thread safe

### ISSUE THREAD

**Issue by MrPowerGamerBR** [s1monw1/KtsRunner#2]
This is more an PSA than anything else, I'm using KtsRunner on my project (very nifty tool btw! Thanks for creating it!) and I found out that, if you try loading two classes on different threads with KtsRunner at the same time... it will throw some very cryptic compilation exceptions.

To fix it I just made the `engine` not static.

**Comment by s1monw1** [comment]
thanks, changed this in new version
