### ISSUE TITLE
Update to Kotlin 1.4

### ISSUE THREAD

**Issue by benediktschwab** [s1monw1/KtsRunner#7]
Hi,

thanks for sharing this great library!

Would it be possible to update the Kotlin version to 1.4?
I'm currently updating my own project to 1.4 and gradle throws the warning of mixing 1.3.70 and 1.4.10 during building.

BR
Benedikt

**Comment by tobiaswx** [comment]
Possibly the update will be available soon, see #8

**Comment by s1monw1** [comment]
Updated to 1.4.20 with library version [0.0.9](https://github.com/s1monw1/KtsRunner/releases/tag/v0.0.9)
